# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('organizationalTag', models.CharField(blank=True, max_length=100, null=True)),
                ('manPartNumber', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateImplemented', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='inventory.Manufacturer'),
        ),
    ]
