# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20161121_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dateImplemented',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturerPartNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='organizationalTag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
