# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20161121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manufacturerPartNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='organizationalTag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
